### ISSUE TITLE
Error in parser.rb:383:in `===': invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by castus** [supermarin/xcpretty#219]
XCPretty is causing an error in parser.rb. Stack trace:

```
/Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.2/lib/xcpretty/parser.rb:383:in '===': invalid byte sequence in US-ASCII (ArgumentError)
from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.2/lib/xcpretty/parser.rb:383:in 'update_test_state'
from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.2/lib/xcpretty/parser.rb:270:in 'parse'
from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.2/lib/xcpretty/formatters/formatter.rb:83:in 'pretty_format'
from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.2/lib/xcpretty/printer.rb:15:in 'pretty_print'
from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.2/bin/xcpretty:80:in 'block in <top (required)>'
from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.2/bin/xcpretty:79:in 'each_line'
from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.2/bin/xcpretty:79:in '<top (required)>'
from /usr/local/bin/xcpretty:23:in 'load'
from /usr/local/bin/xcpretty:23:in '<main>'
```

Execution:
```
    xcodebuild \
      -workspace $XCODE_WORKSPACE.xcworkspace \
      -scheme $XCODE_SCHEME \
      -sdk iphonesimulator \
      -destination "id=$UDID" \
       clean build test | xcpretty -r junit -r html
```

Xcode: 7.3.1

**Comment by castus** [comment]
Solved, I need to set env variable

`LC_ALL="en_US.UTF-8"`

**Comment by jjacquet** [comment]
unreal, but wonderful find, thank you
