### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by lasconic** [supermarin/xcpretty#229]
Not really sure what's happening but I do have a stack trace. Any clue?

```
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/psych-2.0.17/lib/psych.bundle: [BUG] Segmentation fault
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.
-- Control frame information -----------------------------------------------
c:0029 p:-17536842405026 s:0142 e:000141 TOP    [FINISH]
c:0028 p:---- s:0140 e:000139 CFUNC  :require
c:0027 p:0115 s:0136 e:000135 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0026 p:0028 s:0126 e:000125 TOP    /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/psych-2.0.17/lib/psych.rb:6 [FINISH]
c:0025 p:---- s:0124 e:000123 CFUNC  :require
c:0024 p:0115 s:0120 e:000119 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0023 p:0009 s:0110 e:000109 TOP    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/yaml.rb:5 [FINISH]
c:0022 p:---- s:0108 e:000107 CFUNC  :require
c:0021 p:0115 s:0104 e:000103 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0020 p:0007 s:0094 e:000093 TOP    /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rouge-1.10.1/lib/rouge/lexers/apache.rb:1 [FINISH]
c:0019 p:---- s:0092 e:000091 CFUNC  :load
c:0018 p:0063 s:0088 e:000087 METHOD /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rouge-1.10.1/lib/rouge/lexer.rb:443
c:0017 p:0032 s:0083 e:000082 BLOCK  /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rouge-1.10.1/lib/rouge.rb:45 [FINISH]
c:0016 p:---- s:0080 e:000079 CFUNC  :each
c:0015 p:0148 s:0077 e:000076 TOP    /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rouge-1.10.1/lib/rouge.rb:44 [FINISH]
c:0014 p:---- s:0073 e:000072 CFUNC  :require
c:0013 p:0115 s:0069 e:000068 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0012 p:0009 s:0059 e:000058 TOP    /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.2/lib/xcpretty/syntax.rb:2 [FINISH]
c:0011 p:---- s:0057 e:000056 CFUNC  :require
c:0010 p:0115 s:0053 e:000052 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0009 p:0023 s:0043 e:000042 TOP    /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.2/lib/xcpretty.rb:3 [FINISH]
c:0008 p:---- s:0041 e:000040 CFUNC  :require
c:0007 p:0115 s:0037 e:000036 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0006 p:0060 s:0027 e:000026 TOP    /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.2/bin/xcpretty:10 [FINISH]
c:0005 p:---- s:0019 e:000018 CFUNC  :load
c:0004 p:0134 s:0015 E:000448 EVAL   /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/xcpretty:23 [FINISH]
c:0003 p:---- s:0011 e:000010 CFUNC  :eval
c:0002 p:0118 s:0005 E:0003e0 EVAL   /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15 [FINISH]
c:0001 p:0000 s:0002 E:001f18 TOP    [FINISH]
/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/xcpretty:23:in `<main>'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/xcpretty:23:in `load'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.2/bin/xcpretty:10:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.2/lib/xcpretty.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.2/lib/xcpretty/syntax.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rouge-1.10.1/lib/rouge.rb:44:in `<top (required)>'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rouge-1.10.1/lib/rouge.rb:44:in `each'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rouge-1.10.1/lib/rouge.rb:45:in `block in <top (required)>'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rouge-1.10.1/lib/rouge/lexer.rb:443:in `load_lexer'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rouge-1.10.1/lib/rouge/lexer.rb:443:in `load'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rouge-1.10.1/lib/rouge/lexers/apache.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/yaml.rb:5:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/psych-2.0.17/lib/psych.rb:6:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-- C level backtrace information -------------------------------------------
-- Other runtime information -----------------------------------------------
* Loaded script: /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/xcpretty
* Loaded features:
    0 enumerator.so
    1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/encdb.bundle
    2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/trans/transdb.bundle
    3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb
    4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/compatibility.rb
    5 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/defaults.rb
    6 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/deprecate.rb
    7 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/errors.rb
    8 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb
    9 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/requirement.rb
   10 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/platform.rb
   11 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb
   12 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/exceptions.rb
   13 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
   14 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb
   15 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb
   16 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
   17 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb
   18 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/path_support.rb
   19 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb
   20 /Users/travis/.rvm/gems/ruby-2.0.0-p648@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb
   21 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/etc.bundle
   22 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb
   23 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/pathname.bundle
   24 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb
   25 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/environment_preserver.rb
   26 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/user_interaction.rb
   27 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/cgi/core.rb
   28 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/cgi/util.rb
   29 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/cgi/cookie.rb
   30 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/cgi.rb
   31 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb
   32 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/generic.rb
   33 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/ftp.rb
   34 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/http.rb
   35 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/https.rb
   36 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/ldap.rb
   37 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/ldaps.rb
   38 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/mailto.rb
   39 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri.rb
   40 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/socket.bundle
   41 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/socket.rb
   42 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/fcntl.bundle
   43 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb
   44 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/digest.bundle
   45 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb
   46 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/openssl.bundle
   47 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/bn.rb
   48 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/cipher.rb
   49 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/stringio.bundle
   50 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/config.rb
   51 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/digest.rb
   52 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/x509.rb
   53 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb
   54 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/ssl.rb
   55 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl.rb
   56 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/securerandom.rb
   57 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/resolv.rb
   58 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/remote_fetcher.rb
   59 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/gem_remote_fetcher.rb
   60 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/gem_helpers.rb
   61 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/match_platform.rb
   62 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/rubygems_ext.rb
   63 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/config_file.rb
   64 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/rubygems_integration.rb
   65 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/version.rb
   66 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/constants.rb
   67 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/current_ruby.rb
   68 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler/errors.rb
   69 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.2/lib/bundler.rb
   70 /Users/travis/.rvm/gems/ruby-2.0.0-p648@global/gems/bundler-unload-1.0.2/lib/bundler-unload.rb
   71 /Users/travis/.rvm/gems/ruby-2.0.0-p648@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb
   72 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.2/lib/xcpretty/version.rb
   73 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.2/lib/xcpretty/ansi.rb
   74 /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.2/lib/xcpretty/printer.rb
   75 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/strscan.bundle
   76 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html
```

**Comment by paroj** [comment]
https://github.com/travis-ci/travis-ci/issues/5554

**Comment by supermarin** [comment]
Duplicate, not an xcpretty bug
