### ISSUE TITLE
Crash when attempting to parse results of a failed test

### ISSUE THREAD

**Issue by dzzh** [supermarin/xcpretty#241]
I see this error in build log when one of our unit tests fails.

```
[11:24:39]: ▸ /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/syntax.rb:24:in `highlight_with_formatter': undefined method `include?' for nil:NilClass (NoMethodError)
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/syntax.rb:15:in `highlight'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:171:in `format_failure'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:157:in `block (2 levels) in format_failures'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:156:in `map'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:156:in `block in format_failures'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:155:in `each'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:155:in `map'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:155:in `format_failures'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:101:in `format_test_summary'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/parser.rb:563:in `format_summary_if_needed'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/parser.rb:336:in `parse'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:87:in `pretty_format'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/lib/xcpretty/printer.rb:19:in `pretty_print'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/bin/xcpretty:84:in `block in <top (required)>'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/bin/xcpretty:83:in `each_line'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.3/bin/xcpretty:83:in `<top (required)>'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/bin/xcpretty:23:in `load'
[11:24:39]: ▸ from /Users/fenek/.rbenv/versions/2.2.3/bin/xcpretty:23:in `<main>'
[11:40:04]: ▸ Failing tests:
[11:40:04]: ▸ -[MADBleComponentTests testPacketTruncation10]
[11:40:04]: ▸ ** TEST FAILED **
```

**Comment by patdnk** [comment]
Ditto

**Comment by supermarin** [comment]
which xcpretty version?

**Comment by dzzh** [comment]
0.2.3

**Comment by supermarin** [comment]
crap, sounds like we introduced a regression. will push a fix - would you mind pasting   gist of your `xcodebuild.log`?

**Comment by dzzh** [comment]
Here's the output from a failing test file. Is this enough or you need in a full log?

```
Test Case '-[MADBleHelpersTests testPhoneNameToHashcodeOneSymbol]' started.
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
Test Case '-[MADBleHelpersTests testPhoneNameToHashcodeOneSymbol]' passed (0.011 seconds).
Test Case '-[MADBleHelpersTests testPhoneNameToHashcodeOneWord]' started.
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
/Users/zaleznic/Projects/mydrive/mydrive-ios-1/MyDrivePNDTests/BLE/MADBleHelpersTests.m:441: error: -[MADBleHelpersTests testPhoneNameToHashcodeOneWord] : ((expected) equal to (hashcode)) failed: ("149155328") is not equal to ("1491553289")
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
Test Case '-[MADBleHelpersTests testPhoneNameToHashcodeOneWord]' failed (0.012 seconds).
Test Case '-[MADBleHelpersTests testPhoneNameToHashcodeRegularIphoneName]' started.
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
Test Case '-[MADBleHelpersTests testPhoneNameToHashcodeRegularIphoneName]' passed (0.012 seconds).
```

**Comment by supermarin** [comment]
not sure this is enough, it doesn't crash it on my machine: 

```
$ pbpaste | xcpretty
    ✓ testPhoneNameToHashcodeOneSymbol (0.011 seconds)
    ✗ testPhoneNameToHashcodeOneWord, ((expected) equal to (hashcode)) failed: ("149155328") is not equal to ("1491553289")
    ✗ testPhoneNameToHashcodeOneWord,
    ✓ testPhoneNameToHashcodeRegularIphoneName (0.012 seconds)
$
```

**Comment by supermarin** [comment]
You can test out which part of the log crashes it manually by copying the log and `pbpaste | xcpretty`

**Comment by dzzh** [comment]
This should (not) work

```
Test Case '-[XMLDictionaryParserTests testValidElementByNameSmallXML]' started.
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
Test Case '-[XMLDictionaryParserTests testValidElementByNameSmallXML]' passed (0.009 seconds).
Test Case '-[MADBleHelpersTests testPhoneNameToHashcodeOneWord]' started.
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
/Users/zaleznic/Projects/mydrive/mydrive-ios-1/MyDrivePNDTests/BLE/MADBleHelpersTests.m:441: error: -[MADBleHelpersTests testPhoneNameToHashcodeOneWord] : ((expected) equal to (hashcode)) failed: ("149155328") is not equal to ("1491553289")
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
[W] main-thread: ⟨MADAppStateSwitcher.m:261⟩: PND: PND connection type was unset, will set to Unknown
Test Case '-[MADBleHelpersTests testPhoneNameToHashcodeOneWord]' failed (0.012 seconds).
Test Suite 'XMLDictionaryParserTests' passed at 2016-09-29 17:06:13.316.
	 Executed 6 tests, with 0 failures (0 unexpected) in 0.038 (0.041) seconds
Test Suite 'MyDriveUSTests.xctest' failed at 2016-09-29 17:06:13.316.
	 Executed 412 tests, with 1 failure (0 unexpected) in 109.056 (109.324) seconds
Test Suite 'All tests' failed at 2016-09-29 17:06:13.318.
	 Executed 412 tests, with 1 failure (0 unexpected) in 109.056 (109.326) seconds
```

**Comment by dzzh** [comment]
xcpretty is able to output the failing test result immediately after the test fails, it crashes only after the whole suite has completed.

**Comment by supermarin** [comment]
thank you, that's it!

**Comment by dzzh** [comment]
Also notice that xcpretty reports failed test twice, sounds like another bug to me, or at least a symptome of this one.

**Comment by supermarin** [comment]
which test framework are you using,if any?

**Comment by dzzh** [comment]
XCTest + OCMock

**Comment by kirillzh** [comment]
Same here with Swift 3 tests using EarlGrey (uses XCTest).

**Comment by AliSoftware** [comment]
Confirmed too.

I have a Travis build matrix and all tests pass without crashing `xcpretty` when run with Swift 2.2 on Xcode 7, but Crash when testing my code with Swift 3 / Xcode 8 with the same message.

See for example [this build log of OHHTTPStubs on travis](https://travis-ci.org/AliSoftware/OHHTTPStubs/jobs/164977782)

<details>
<summary>Stacktrace</summary>

```
[…snip…]
WithContentsOfURLTests
    ✓ test_NSData_dataWithContentsOfURL_mainQueue (0.616 seconds)
    ✓ test_NSData_dataWithContentsOfURL_parallelQueue (0.647 seconds)
    ✓ test_NSString_stringWithContentsOfURL_mainQueue (0.636 seconds)
    ✓ test_NSString_stringWithContentsOfURL_parallelQueue (0.621 seconds)
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/syntax.rb:24:in `highlight_with_formatter': undefined method `include?' for nil:NilClass (NoMethodError)
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/syntax.rb:15:in `highlight'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:171:in `format_failure'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:157:in `block (2 levels) in format_failures'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:156:in `map'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:156:in `block in format_failures'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:155:in `each'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:155:in `map'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:155:in `format_failures'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:101:in `format_test_summary'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/parser.rb:563:in `format_summary_if_needed'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/parser.rb:336:in `parse'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:87:in `pretty_format'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/printer.rb:19:in `pretty_print'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/bin/xcpretty:84:in `block in <top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/bin/xcpretty:83:in `each_line'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/bin/xcpretty:83:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/xcpretty:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/xcpretty:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
```
</details>

**Comment by supermarin** [comment]
@AliSoftware sorry for the delay - I'll in the worst case revert the last contribution while working on rewrite. 
Let's timebox  release 0.2.4 by end of tomorrow PST

**Comment by AliSoftware** [comment]
@supermarin no worries; you have better reactivity on this PR than I currently have on my various OSS projects anyway given how busy I am ^^

**Comment by supermarin** [comment]
0.2.4 released with fix
