### ISSUE TITLE
Error: compile_commands.json not found at current location.

### ISSUE THREAD

**Issue by loveace** [supermarin/xcpretty#259]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': Permission denied - /path (Errno::EACCES)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/lib/xcpretty/reporters/reporter.rb:29:in `finish'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/bin/xcpretty:89:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/bin/xcpretty:89:in `<top (required)>'
	from /usr/local/bin/xcpretty:23:in `load'
	from /usr/local/bin/xcpretty:23:in `<main>'
Error: compile_commands.json not found at current location.
Command /bin/sh failed with exit code 98

**Comment by supermarin** [comment]
how do you invoke xcpretty?

**Comment by abdullahselek** [comment]
I have the same issue, the commands that I tried are like this
```xcodebuild | xcpretty -r json-compilation-database```
and 
```xcodebuild -workspace WORKSPACE_NAME.xcworkspace -scheme SCHEME | xcpretty -r json-compilation-database```

**Comment by abdullahselek** [comment]
I found the solution this is worked for me
```xcodebuild -workspace WORK_SPACE.xcworkspace -scheme SCHEME | xcpretty -r json-compilation-database --output compile_commands.json```

**Comment by supermarin** [comment]
Will keep the issue open until we provide a better default error message, but @abdullahselek's answer is the right solution

**Comment by GipsySh** [comment]
I tried the following commands:
`xcodebuild -target TARGET -configuration Debug -scheme SCHEME | xcpretty --report json-compilation-database --output compile_commands.json`
or
`xcodebuild -target TARGET -configuration Debug -scheme SCHEME | xcpretty -r json-compilation-database --output compile_commands.json`

But I got "Error: compile_commands.json not found at current location." for both.
It seems @abdullahselek 's solution doesn't work for me.

**Comment by GipsySh** [comment]
@supermarin Can you explain what is the possible reason of the problem, please? It seems from your comment that this one is only in the message text. 
But compile_commands.json was not really created in my project directory on some Macs. The file was created at one Mac, but then it was the error Skipping <Path>. Compile command not found.

**Comment by supermarin** [comment]
@GipsySh I'll need a full stack trace in order to help you.
Also, what's the output of `$ pwd` and `$ ls -la` in the directory you're running this from?

**Comment by GipsySh** [comment]
@supermarin Here is output of $ pwd and $ ls -la in the directory I'm running this from. 
Unfortunately, I have to hide my project file names because it's my working project and some of the names are matched with our company products names. But I hope the file names doesn't sense for the error analyzing.

```
Yulias-Mac-mini:rosing-ios yulia$ pwd
/Users/yulia/Documents/<DirName>
Yulias-Mac-mini:<DirName> yulia$ ls -la
total 360
drwxr-xr-x   52 yulia  staff   1768 Apr 11 16:41 .
drwx------+  14 yulia  staff    476 Apr 11 12:43 ..
-rw-r--r--@   1 yulia  staff  14340 Apr 14 12:39 .DS_Store
drwxr-xr-x   15 yulia  staff    510 Apr 14 12:32 .git
-rw-r--r--    1 yulia  staff     34 Mar 23 00:01 .gitattributes
-rw-r--r--    1 yulia  staff     81 Apr  5 11:20 .gitignore
-rw-r--r--    1 yulia  staff   1422 Apr  5 11:20 .gitmodules
drwxr-xr-x    4 yulia  staff    136 Jan 19 21:59 <Name>
-rw-r--r--    1 yulia  staff   3357 Jan 19 21:59 <Name>.plist
drwxr-xr-x   18 yulia  staff    612 Jan 25 23:47 <Name>.xcassets
drwxr-xr-x   18 yulia  staff    612 Jan 25 23:47 <Name>.xcassets
-rw-r--r--    1 yulia  staff   3389 Jan 19 21:59 <Name>.plist
drwxr-xr-x    4 yulia  staff    136 Jan 19 21:59 <Name>
drwxr-xr-x  473 yulia  staff  16082 Apr 11 13:24 <Name>
drwxr-xr-x   10 yulia  staff    340 Jan 25 23:47 Crashlytics.framework
-rw-r--r--    1 yulia  staff    225 Jan 19 21:55 Entitlements.plist
drwxr-xr-x    9 yulia  staff    306 Jan 25 23:47 Fabric.framework
-rw-r--r--    1 yulia  staff    943 Mar 23 00:01 <Name>.md
drwxr-xr-x   18 yulia  staff    612 Jan 25 23:47 <Name>.xcassets
-rw-r--r--    1 yulia  staff   3363 Jan 19 21:59 <Name>.plist
drwxr-xr-x   18 yulia  staff    612 Jan 25 23:47 <Name>.xcassets
drwxr-xr-x   15 yulia  staff    510 Jan 19 21:55 <Name>
drwxr-xr-x    6 yulia  staff    204 Jan 25 23:47 <Name>.framework
-rw-r--r--    1 yulia  staff   1765 Jan 19 21:55 <Name>.md
drwxr-xr-x   20 yulia  staff    680 Mar 23 00:01 Resources
-rw-r--r--    1 yulia  staff    104 Jan 19 21:55 <Name>.h
-rw-r--r--    1 yulia  staff   3341 Jan 19 21:59 <Name>.plist
-rw-r--r--    1 yulia  staff    476 Mar 23 00:01 <Name>.pch
drwxr-xr-x    8 yulia  staff    272 Apr 14 12:29 <Name>.xcodeproj
drwxr-xr-x    4 yulia  staff    136 Jan 19 21:55 <Name>
drwxr-xr-x   14 yulia  staff    476 Jan 25 23:47 <Name>
-rw-r--r--    1 yulia  staff    469 Jan 19 21:55 <Name>.entitlements
drwxr-xr-x   17 yulia  staff    578 Mar 23 00:01 <Name>.xcassets
-rw-r--r--    1 yulia  staff   3379 Mar 23 00:01 <Name>.plist
drwxr-xr-x    5 yulia  staff    170 Mar 23 00:01 <Name>
drwxr-xr-x   14 yulia  staff    476 Jan 20 01:10 <Name>
-rw-r--r--    1 yulia  staff   3351 Mar 23 00:01 <Name>.plist
drwxr-xr-x   19 yulia  staff    646 Jan 25 23:47 <Name>.xcassets
-rw-r--r--    1 yulia  staff   3178 Jan 19 21:55 <Name>.h
-rw-r--r--    1 yulia  staff  38071 Apr 11 13:24 <Name>.h
drwxr-xr-x    7 yulia  staff    238 Apr  5 11:21 <Name>
drwxr-xr-x   18 yulia  staff    612 Jan 25 23:47 <Name>.xcassets
drwxr-xr-x@  12 yulia  staff    408 Apr 14 12:35 <Name>
-rw-r--r--    1 yulia  staff  18663 Jan 19 21:55 <Name>.json
-rw-r--r--    1 yulia  staff  19574 Mar 23 00:01 <Name>.json
-rw-r--r--    1 yulia  staff   3361 Jan 19 21:55 <Name>.plist
drwxr-xr-x   18 yulia  staff    612 Jan 25 23:47 <Name>.xcassets
-rw-r--r--    1 yulia  staff      9 Mar 23 00:01 readme.md
-rwxr-xr-x    1 yulia  staff   1892 Apr  5 11:21 <Name>.sh
-rw-r--r--    1 yulia  staff    169 Jan 19 21:55 <Name>.sh
-rw-r--r--    1 yulia  staff   3359 Jan 19 21:59 <Name>.plist
drwxr-xr-x   15 yulia  staff    510 Jan 25 23:47 www
```

**Comment by GipsySh** [comment]
@supermarin Could you tell how to get oclink full stack trace?

**Comment by supermarin** [comment]
Not sure what `oclink` is. Given your paths are obscured, is there any spaces in the full path (or project name)?

**Comment by GipsySh** [comment]
@supermarin Yes, two .xcassets files names contain spaces. Should I renamed them to exclude spaces?

**Comment by supermarin** [comment]
Nope, nested files shouldn't make trouble, I was mostly curious about the base directory (`<DirName>`). I'll need to look into this, but don't have capacity ATM.

**Comment by GipsySh** [comment]
@supermarin Sorry, what does ATM here mean?
