### ISSUE TITLE
XCpretty is receiving error in parser.rb 

### ISSUE THREAD

**Issue by gangadharbonda** [supermarin/xcpretty#306]
Receiving following error when running Xcodebuild command with xcpretty  and the command used is as follows 

xcodebuild test -scheme $SCHEME -destination $PLATFORM_DEVICEINFO -resultBundlePath '$PWD/' -only-testing:$TEST_LIVE  | tee xcodebuild.log | /usr/local/bin/xcpretty --report html

/Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/lib/xcpretty/parser.rb:429:in `===': invalid byte sequence in US-ASCII (ArgumentError)
	from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/lib/xcpretty/parser.rb:429:in `update_test_state'
	from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/lib/xcpretty/parser.rb:304:in `parse'
	from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/lib/xcpretty/formatters/formatter.rb:87:in `pretty_format'
	from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/lib/xcpretty/printer.rb:19:in `pretty_print'
	from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/bin/xcpretty:84:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/bin/xcpretty:83:in `each_line'
	from /Library/Ruby/Gems/2.3.0/gems/xcpretty-0.2.8/bin/xcpretty:83:in `<top (required)>'
	from /usr/local/bin/xcpretty:22:in `load'
	from /usr/local/bin/xcpretty:22:in `<main>'
MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:

**Comment by gangadharbonda** [comment]
@supermarin 

Hi , Can you take a look at this issue. Let me know if you need more information

**Comment by pawankums** [comment]
any solution for it, i am facing same issue.

**Comment by pawankums** [comment]
if you are hitting above command through jenkins using bash script.. add 
export LC_CTYPE=en_US.UTF-8

in your bash file

**Comment by jeiea** [comment]
I understand that there's a simple workaround, but it's just that—a workaround. There are quite a few issues outlined [here](https://github.com/xcpretty/xcpretty/issues?q=is%3Aissue+invalid+ascii+is%3Aclosed), and I believe that there's a better solution to address them.
