### ISSUE TITLE
US-ASCII encoding problems

### ISSUE THREAD

**Issue by delebedev** [supermarin/xcpretty#48]
during test I get the following exception:
`/Users/admin/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/gems/2.0.0/gems/xcpretty-0.1.0/lib/xcpretty.rb:25:in `=~': invalid byte sequence in US-ASCII (ArgumentError)
[15:07:47][Step 4/9]    from /Users/admin/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/gems/2.0.0/gems/xcpretty-0.1.0/lib/xcpretty.rb:25:in `block in handle'
[15:07:47][Step 4/9]    from /Users/admin/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/gems/2.0.0/gems/xcpretty-0.1.0/lib/xcpretty.rb:24:in `each'
[15:07:47][Step 4/9]    from /Users/admin/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/gems/2.0.0/gems/xcpretty-0.1.0/lib/xcpretty.rb:24:in `detect'
[15:07:47][Step 4/9]    from /Users/admin/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/gems/2.0.0/gems/xcpretty-0.1.0/lib/xcpretty.rb:24:in `handle'
[15:07:47][Step 4/9]    from /Users/admin/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/gems/2.0.0/gems/xcpretty-0.1.0/bin/xcpretty:66:in `block in <top (required)>'
[15:07:47][Step 4/9]    from /Users/admin/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/gems/2.0.0/gems/xcpretty-0.1.0/bin/xcpretty:65:in `each_line'
[15:07:47][Step 4/9]    from /Users/admin/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/gems/2.0.0/gems/xcpretty-0.1.0/bin/xcpretty:65:in `each_line'
[15:07:47][Step 4/9]    from /Users/admin/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/gems/2.0.0/gems/xcpretty-0.1.0/bin/xcpretty:65:in `<top (required)>'
[15:07:47][Step 4/9]    from /Users/admin/.rvm/gems/ruby-2.0.0-p247/bin/xcpretty:23:in `load'
[15:07:47][Step 4/9]    from /Users/admin/.rvm/gems/ruby-2.0.0-p247/bin/xcpretty:23:in `<main>'
[15:07:47][Step 4/9]    from /Users/admin/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
[15:07:47][Step 4/9]    from /Users/admin/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'`

Probably it's related to https://github.com/mneorr/XCPretty/issues/36.
What kind of information can I provide in addition?

**Comment by ThuggishNuggets** [comment]
This fixed this issue for us. Thanks!

**Comment by via-guy** [comment]
Same, thank you!
